sudo: false
language: python
python:
  - "2.7"
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
script:
  - pep8 p2bf/
  - coverage run --source=./ test.py
after_script:
  - coveralls
